sudo: false
language: python
python:
  - "2.7"
install:
    - pip install -r requirements.txt
    - pip install -r dev_requirements.txt
    - pip install coveralls
script:
    ./build
after_success:
    coveralls

