#!/bin/bash
#
# Build script to validate greenpithumb frontend

# Exit build script on first failure
set -e

# Run unit tests and calculate code coverage.
coverage run \
  --source server \
  --omit server/greenpithumb \
  -m unittest discover tests


# Check that source has correct formatting.
yapf \
  --diff \
  --recursive \
  --style google \
  ./ \
  --exclude "./third_party/*" \
  --exclude "./server/greenpithumb/*"

# Run static analysis for Python bugs/cruft.
pyflakes server/*.py tests/*.py

# Check that docstrings are formatted correctly.
PYTHONPATH=$PYTHONPATH:$(pwd)/third_party/docstringchecker \
  pylint --reports=n server tests
